### ISSUE TITLE
Zigbee2mqtt fails to configure Develco SMSZB-120

### ISSUE THREAD

**Issue by jomaskm** [Koenkk/zigbee-OTA#224]
Coordinator: Conbee II

I have four of these models (Develco SMSZB-120) in the house. They each have had different firmwares, but have the same issue in Z2M.

Also, they pair and work just fine in ZHA and deconz. I've used both of those before discovering Z2M.

They pair ok, but only one of them gives readings on "temperature", "reliability" and "fault".
The one that seems to be ok, also gives this error though. It goes through 3 attempts without success.

Things I have tried:

- Pairing close to the coordinator, with Z2M set to only allow pairing through coordinator.
- Pairing through an assortement of routers.
- Factory reset the smoke detector countless times (it can only be force removed btw.)

Are there any more detailed logs I can provide that would provide more insight?

`2022-12-31 14:14:47Failed to configure '0x0015bc003100549e', attempt 1 (Error: Bind 0x0015bc003100549e/35 genBasic from '0x00212effff0676cd/1' failed (Error: status: 140) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/develco.js:436:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))`

**Comment by jomaskm** [comment]
Apologies for posting this in the wrong place. I however managed to get them to work properly now. They seem to report correct values again after many many pairings. Updated the firmware of the coordinator (conbee II) as well to the May 2022-version.
Tested working with the newest 4.0.5 fw on the smoke detectors.
