### ISSUE TITLE
code: 'ERR_BUFFER_OUT_OF_BOUNDS' when running scripts/add.js

### ISSUE THREAD

**Issue by kalon33** [Koenkk/zigbee-OTA#430]
Running the add.js script to add OTA files for Lixee ZiPulses:

`node scripts/add.js https://github.com/fairecasoimeme/ZiPulses/releases/download/v6.0/ZiPulses_v6.0.bin`

I got this error:

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:405:5)
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt16LE (node:internal/buffer:245:5)
    at Object.parseImage (/home/nicolas/sources/zigbee-OTA/lib/ota.js:17:34)
    at main (/home/nicolas/sources/zigbee-OTA/scripts/add.js:101:28)
    at Object.<anonymous> (/home/nicolas/sources/zigbee-OTA/scripts/add.js:173:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

I tried to upgrade default Ubuntu 22.04 version to v18.19.0 from NodeSource, but still I got the same error.

Isn't it possible to add it? The error is not really meaningful for me.

Thanks for your help!

**Comment by kalon33** [comment]
Sorry, I finally found my answer on the product github: no OTA file provided.
